import Mathlib
import Mathlib.MeasureTheory.Constructions.Polish.Basic

open TopologicalSpace
open Set Topology MeasureTheory
open scoped Topology

namespace Appendix1

/-- The unit interval `[0,1]` as a type. -/
abbrev Icc01 : Type :=
  Set.Icc (0 : ℝ) (1 : ℝ)

/-- Kallenberg's `[0,1]^∞`, indexed by `ℕ`. -/
abbrev HilbertCube : Type :=
  ℕ → Icc01


/-!
# Basic facts about the Hilbert cube

These are mostly Mathlib-instance facts, but it is useful to name them explicitly.
-/

/-- The Hilbert cube is compact. -/
theorem hilbertCube_compactSpace :
    CompactSpace HilbertCube := by
  infer_instance

/-- The Hilbert cube is Hausdorff. -/
theorem hilbertCube_t2Space :
    T2Space HilbertCube := by
  infer_instance

/-- The Hilbert cube is second countable. -/
theorem hilbertCube_secondCountable :
    SecondCountableTopology HilbertCube := by
  infer_instance

/-- The Borel measurable space on the Hilbert cube is generated by its topology. -/
theorem hilbertCube_opensMeasurableSpace :
    OpensMeasurableSpace HilbertCube := by
  infer_instance


/-!
# The concrete metric embedding

For a separable metric space `X`, choose a dense sequence `a : ℕ → X`.
Map

`x ↦ (n ↦ dist x (a n) / (1 + dist x (a n)))`.

This lands in `[0,1]^ℕ`.
-/

noncomputable section

/-- The bounded distance coordinate map associated to a sequence `a : ℕ → X`. -/
def boundedDistanceEmbeddingMap
    {X : Type*} [PseudoMetricSpace X]
    (a : ℕ → X) :
    X → HilbertCube :=
  fun x n =>
    have hd : 0 ≤ dist x (a n) := dist_nonneg
    have hpos : 0 < 1 + dist x (a n) := by linarith
    ⟨dist x (a n) / (1 + dist x (a n)),
      div_nonneg hd (by linarith),
      (div_le_one hpos).mpr (by linarith)⟩

/-- Each bounded distance coordinate is continuous. -/
theorem continuous_boundedDistanceEmbeddingMap
    {X : Type*} [PseudoMetricSpace X]
    (a : ℕ → X) :
    Continuous (boundedDistanceEmbeddingMap a) := by
  rw [continuous_pi_iff]
  intro n
  have h_dist : Continuous (fun x : X => dist x (a n)) :=
    continuous_dist.comp (continuous_id.prodMk continuous_const)
  have h_cont : Continuous (fun x : X => dist x (a n) / (1 + dist x (a n))) := by
    refine Continuous.div h_dist ?_ ?_
    · exact continuous_const.add h_dist
    · intro x
      have hd : 0 ≤ dist x (a n) := dist_nonneg
      linarith
  simpa [Icc01, boundedDistanceEmbeddingMap] using
    (Continuous.subtype_mk h_cont (fun x => by
      have hd : 0 ≤ dist x (a n) := dist_nonneg
      have hpos : 0 < 1 + dist x (a n) := by linarith
      have hdiv_nonneg : 0 ≤ dist x (a n) / (1 + dist x (a n)) := div_nonneg hd (by linarith)
      have hdiv_le_one : dist x (a n) / (1 + dist x (a n)) ≤ 1 :=
        (div_le_one hpos).mpr (by linarith)
      exact ⟨hdiv_nonneg, hdiv_le_one⟩))

/--
If `a` has dense range, then the bounded distance map is injective.

Mathematically: if all distances to a dense set agree, then the two points agree.
-/
theorem injective_boundedDistanceEmbeddingMap_of_denseRange
    {X : Type*} [PseudoMetricSpace X] [T0Space X]
    {a : ℕ → X}
    (ha : DenseRange a) :
    Function.Injective (boundedDistanceEmbeddingMap a) := by
  intro x y h
  have h_eq : ∀ n, dist x (a n) / (1 + dist x (a n)) = dist y (a n) / (1 + dist y (a n)) := by
    intro n
    have := congrArg (fun f : HilbertCube => f n) h
    simpa [boundedDistanceEmbeddingMap] using this
  have h_dist_eq : ∀ n, dist x (a n) = dist y (a n) := by
    intro n
    have hx : 0 ≤ dist x (a n) := dist_nonneg
    have hy : 0 ≤ dist y (a n) := dist_nonneg
    have h_eq' := h_eq n
    -- From t/(1+t) = s/(1+s), we get t = s
    field_simp at h_eq'
    linarith
  have h_dist_zero : dist x y = 0 := by
    have : ∀ ε > 0, dist x y < 2 * ε := by
      intro ε hε
      obtain ⟨n, hn⟩ := ha.exists_dist_lt x hε
      have h_eq_dist := h_dist_eq n
      calc
        dist x y ≤ dist x (a n) + dist (a n) y := dist_triangle _ _ _
        _ = dist x (a n) + dist y (a n) := by rw [dist_comm (a n) y]
        _ = dist x (a n) + dist x (a n) := by rw [h_eq_dist]
        _ = 2 * dist x (a n) := by ring
        _ < 2 * ε := by nlinarith
    -- If dist x y < 2*ε for all ε > 0, then dist x y = 0
    by_contra! hpos
    have hpos' : dist x y > 0 := dist_nonneg.lt_of_ne hpos.symm
    have := this (dist x y / 2) (by linarith)
    nlinarith
  have h_insep : Inseparable x y := (Metric.inseparable_iff.mpr h_dist_zero)
  exact inseparable_iff_eq.mp h_insep

/--
If `a` has dense range, then the bounded distance map is a topological embedding.

This is the main separable-metric-space embedding theorem into `[0,1]^∞`.
-/
theorem isEmbedding_boundedDistanceEmbeddingMap_of_denseRange
    {X : Type*} [PseudoMetricSpace X] [T0Space X]
    {a : ℕ → X}
    (ha : DenseRange a) :
    Topology.IsEmbedding (boundedDistanceEmbeddingMap a) := by
  let f := boundedDistanceEmbeddingMap a
  have h_cont : Continuous f := continuous_boundedDistanceEmbeddingMap a
  have h_inj : Function.Injective f :=
    injective_boundedDistanceEmbeddingMap_of_denseRange ha
  -- The map φ(t) = t/(1+t) has inverse ψ(s) = s/(1-s) on [0,1).
  -- We prove IsInducing via the nhds characterization.
  have h_inducing : Topology.IsInducing f := by
    rw [Topology.isInducing_iff_nhds]
    intro x
    apply le_antisymm
    · -- 𝓝 x ≤ comap f (𝓝 (f x)) is continuity
      exact (h_cont.tendsto x).le_comap
    · -- comap f (𝓝 (f x)) ≤ 𝓝 x
      -- For any U ∈ 𝓝 x, there exists V ∈ 𝓝 (f x) with f⁻¹(V) ⊆ U.
      -- It suffices to find such V for every metric ball around x.
      have h_ind : ∀ ε > 0, ∃ V ∈ 𝓝 (f x), f ⁻¹' V ⊆ Metric.ball x ε := by
        intro ε hε
        -- Pick n with d(x, a_n) < ε/3
        obtain ⟨n, hn⟩ := ha.exists_dist_lt x (by linarith : 0 < ε / 3)
        have hd_x : 0 ≤ dist x (a n) := dist_nonneg
        have hpos_x : 0 < 1 + dist x (a n) := by linarith
        have hv_lt_one : dist x (a n) / (1 + dist x (a n)) < 1 :=
          (div_lt_one hpos_x).mpr (by linarith)
        -- ψ(s) = s/(1-s) is continuous at v = d_x/(1+d_x) since v < 1
        have h_cont_ψ : ContinuousAt (fun (s : ℝ) => s / (1 - s))
            (dist x (a n) / (1 + dist x (a n))) := by
          refine ContinuousAt.div continuous_id.continuousAt ?_ ?_
          · exact (continuous_const.sub continuous_id).continuousAt
          · linarith
        -- By metric continuity, ∃ η > 0 such that |s - v| < η → |ψ(s) - d_x| < ε/3
        obtain ⟨η, hη, hψ⟩ : ∃ η > 0, ∀ s, |s - (dist x (a n) / (1 + dist x (a n)))| < η →
            |s / (1 - s) - dist x (a n)| < ε / 3 := by
          have := Metric.continuousAt_iff.mp h_cont_ψ (ε / 3) (by linarith)
          obtain ⟨η, hη, h⟩ := this
          refine ⟨η, hη, fun s hs => ?_⟩
          have hdist : dist s (dist x (a n) / (1 + dist x (a n))) < η := by
            rw [Real.dist_eq]; exact hs
          have hψdist := h hdist
          rw [Real.dist_eq] at hψdist
          -- hψdist : |s/(1-s) - ψ(v)| < ε/3 where ψ(v) = d_x
          -- ψ(v) = (d_x/(1+d_x))/(1 - d_x/(1+d_x)) = d_x
          have h_eq : (dist x (a n) / (1 + dist x (a n))) /
              (1 - dist x (a n) / (1 + dist x (a n))) = dist x (a n) := by
            field_simp; ring
          rw [h_eq] at hψdist
          exact hψdist
        -- Define V = {y | |y_n - f(x)_n| < η}, an open neighborhood of f x
        let V : Set HilbertCube := {y | |(y n).1 - (f x n).1| < η}
        have hV_open : IsOpen V := by
          have h_cont_coord : Continuous (fun (y : HilbertCube) => (y n).1) :=
            Continuous.comp continuous_subtype_val (continuous_apply n)
          refine IsOpen.preimage h_cont_coord Metric.isOpen_ball
        have hV_mem : V ∈ 𝓝 (f x) := by
          refine IsOpen.mem_nhds hV_open ?_
          dsimp [V]
          have hval : (f x n).1 = dist x (a n) / (1 + dist x (a n)) := rfl
          rw [hval]
          simp [hη]
        have h_preimage : f ⁻¹' V ⊆ Metric.ball x ε := by
          intro y hy
          have hyV : f y ∈ V := hy
          dsimp [V] at hyV
          have h_eq_y : (f y n).1 = dist y (a n) / (1 + dist y (a n)) := rfl
          have h_eq_x : (f x n).1 = dist x (a n) / (1 + dist x (a n)) := rfl
          rw [h_eq_y, h_eq_x] at hyV
          -- hyV : |d_y/(1+d_y) - d_x/(1+d_x)| < η
          -- Apply ψ(s) = s/(1-s) to both sides via hψ
          set d_y := dist y (a n) with hd_y
          set d_x := dist x (a n) with hd_x
          have h_bound : |d_y - d_x| < ε / 3 := by
            -- hψ applied to s = d_y/(1+d_y) gives |ψ(s) - d_x| < ε/3
            -- But ψ(s) = (d_y/(1+d_y))/(1 - d_y/(1+d_y)) = d_y
            have hd_y_nonneg : 0 ≤ d_y := by rw [hd_y]; exact dist_nonneg
            have h_alg : (d_y / (1 + d_y)) / (1 - d_y / (1 + d_y)) = d_y := by
              have h_ne : 1 + d_y ≠ 0 := by linarith
              field_simp [h_ne]
              ring
            have h_ineq : |(d_y / (1 + d_y)) - (d_x / (1 + d_x))| < η := hyV
            have hψ_app := hψ (d_y / (1 + d_y)) h_ineq
            -- hψ_app : |(d_y/(1+d_y))/(1 - d_y/(1+d_y)) - d_x| < ε/3
            rw [h_alg] at hψ_app
            -- hψ_app : |d_y - d_x| < ε/3
            rw [hd_y, hd_x]
            exact hψ_app
          -- Now d(x,y) ≤ d(x,a_n) + d(y,a_n) < ε
          have h_dist_lt : dist x y < ε := by
            calc
              dist x y ≤ dist x (a n) + dist (a n) y := dist_triangle _ _ _
              _ = dist x (a n) + dist y (a n) := by rw [dist_comm (a n) y]
              _ = d_x + d_y := by rw [hd_x, hd_y]
              _ < d_x + (d_x + ε / 3) := by
                have h_tri : d_y < d_x + ε / 3 := by
                  have := abs_lt.mp h_bound
                  linarith
                linarith
              _ = 2 * d_x + ε / 3 := by ring
              _ < 2 * (ε / 3) + ε / 3 := by
                rw [hd_x]
                linarith
              _ = ε := by ring
          rwa [Metric.mem_ball, dist_comm]
        exact ⟨V, hV_mem, h_preimage⟩
      -- Now: 𝓝 x ≤ comap f (𝓝 (f x))
      -- Given U ∈ 𝓝 x, pick ε > 0 with Metric.ball x ε ⊆ U, then use h_ind
      intro U hU
      rcases Metric.mem_nhds_iff.mp hU with ⟨ε, hε, h_ball_sub⟩
      obtain ⟨V, hV, h_sub⟩ := h_ind ε hε
      -- Need to show U ∈ comap f (𝓝 (f x))
      -- This means ∃ W ∈ 𝓝 (f x), f⁻¹(W) ⊆ U
      -- Take W = V
      exact Filter.mem_comap.mpr ⟨V, hV, h_sub.trans h_ball_sub⟩
  exact Topology.IsEmbedding.mk h_inducing h_inj

/--
A nonempty separable pseudo-metric space admits a dense sequence.

This is the countable dense set needed to define the embedding.
-/
theorem exists_dense_sequence
    {X : Type*} [PseudoMetricSpace X]
    [TopologicalSpace.SeparableSpace X] [Nonempty X] :
    ∃ a : ℕ → X, DenseRange a :=
  TopologicalSpace.exists_dense_seq X

/--
Every nonempty separable pseudo-metric `T0` space embeds into the Hilbert cube.
-/
theorem exists_embedding_into_hilbertCube_of_separable_pseudoMetric
    (X : Type*) [PseudoMetricSpace X] [T0Space X]
    [TopologicalSpace.SeparableSpace X] [Nonempty X] :
    ∃ f : X → HilbertCube, Topology.IsEmbedding f := by
  obtain ⟨a, ha⟩ := exists_dense_sequence (X := X)
  refine ⟨boundedDistanceEmbeddingMap a, ?_⟩
  exact isEmbedding_boundedDistanceEmbeddingMap_of_denseRange ha


/-!
# Passing from Polish spaces to metric spaces

A `PolishSpace` in Mathlib is not necessarily given with the concrete metric
we want to use, so the eventual proof would use Mathlib's compatible complete
metric upgrade.
-/

/--
A nonempty Polish space admits a topological embedding into the Hilbert cube.

The proof should:
1. upgrade the Polish topology to a compatible complete metric;
2. use second countability/separability to obtain a dense sequence;
3. apply the bounded-distance embedding above.
-/
theorem exists_embedding_into_hilbertCube_of_polish
    (X : Type*) [TopologicalSpace X] [PolishSpace X] [Nonempty X] :
    ∃ f : X → HilbertCube, Topology.IsEmbedding f := by
  -- Polish spaces are completely metrizable, so we can upgrade to a metric
  letI : MetricSpace X := TopologicalSpace.completelyMetrizableMetric X
  haveI : TopologicalSpace.SeparableSpace X :=
    TopologicalSpace.SecondCountableTopology.to_separableSpace (α := X)
  exact exists_embedding_into_hilbertCube_of_separable_pseudoMetric X


/-!
# Turning an embedding into a homeomorphism with its range

Mathlib's `IsEmbedding` means a map is inducing and injective, i.e. it identifies
the source with a subspace of the target.
-/

/--
An embedding gives a homeomorphism from the source onto its range.
-/
theorem homeomorph_range_of_isEmbedding
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    {f : X → Y}
    (hf : Topology.IsEmbedding f) :
    ∃ e : X ≃ₜ (Set.range f), True := by
  refine ⟨hf.toHomeomorph, ?_⟩
  trivial

/--
The empty space is homeomorphic to the empty subset of the Hilbert cube.
-/
theorem empty_homeomorph_empty_hilbertCube
    {X : Type*} [TopologicalSpace X] [IsEmpty X] :
    ∃ e : X ≃ₜ (∅ : Set HilbertCube), True := by
  haveI : IsEmpty (∅ : Set HilbertCube) := by
    refine ⟨fun s => s.2⟩
  exact ⟨Homeomorph.empty (X := X) (Y := (∅ : Set HilbertCube)), trivial⟩


/-!
# Borelness of the range

This is the Lusin--Souslin step. Mathlib already has essentially this theorem as

`MeasureTheory.measurableSet_range_of_continuous_injective`.
-/

/--
The range of a continuous injective map from a Polish space into a Hausdorff
space with its Borel measurable structure is Borel.
-/
theorem measurableSet_range_of_polish_continuous_injective
    {X Y : Type*}
    [TopologicalSpace X] [PolishSpace X]
    [TopologicalSpace Y] [T2Space Y]
    [MeasurableSpace Y] [OpensMeasurableSpace Y]
    {f : X → Y}
    (hf_cont : Continuous f)
    (hf_inj : Function.Injective f) :
    MeasurableSet (Set.range f) :=
  MeasureTheory.measurableSet_range_of_continuous_injective hf_cont hf_inj

/--
The range of a topological embedding from a Polish space into the Hilbert cube
is a Borel subset of the Hilbert cube.
-/
theorem measurableSet_range_of_polish_embedding_into_hilbertCube
    {X : Type*} [TopologicalSpace X] [PolishSpace X]
    {f : X → HilbertCube}
    (hf : Topology.IsEmbedding f) :
    MeasurableSet (Set.range f) := by
  have h_cont : Continuous f := hf.continuous
  have h_inj : Function.Injective f := hf.injective
  -- The Hilbert cube is T2 and has OpensMeasurableSpace
  haveI : T2Space HilbertCube := hilbertCube_t2Space
  haveI : OpensMeasurableSpace HilbertCube := hilbertCube_opensMeasurableSpace
  exact measurableSet_range_of_polish_continuous_injective h_cont h_inj

/--
Theorem A1.1 (embedding)
Any Polish space is homeomorphic to a Borel subset of the compact space `[0,1]^∞`.
-/
theorem kallenberg_a1_1
    (X : Type*) [TopologicalSpace X] [PolishSpace X] :
    ∃ s : Set HilbertCube, MeasurableSet s ∧ ∃ e : X ≃ₜ s, True := by
  -- First handle the empty case
  by_cases h : Nonempty X
  · -- Nonempty case: get an embedding, then its range is Borel and homeomorphic to X
    obtain ⟨f, hf⟩ := exists_embedding_into_hilbertCube_of_polish X
    have h_meas : MeasurableSet (Set.range f) :=
      measurableSet_range_of_polish_embedding_into_hilbertCube hf
    obtain ⟨e, _⟩ := homeomorph_range_of_isEmbedding hf
    refine ⟨Set.range f, h_meas, ?_⟩
    -- Convert e : X ≃ₜ Set.range f to X ≃ₜ s where s = Set.range f
    -- e is already X ≃ₜ (Set.range f), so we just need to adjust the type
    -- The goal is ∃ e : X ≃ₜ (Set.range f), True
    -- But the goal type is X ≃ₜ s where s = Set.range f
    -- So e is exactly what we need
    -- Actually, the goal is X ≃ₜ s with s being a variable. Let me use `refine ⟨?_, ?_⟩`
    -- The goal after `refine ⟨Set.range f, h_meas, ?_⟩` is `∃ e : X ≃ₜ (Set.range f), True`
    -- Wait, `s` is `Set.range f`, so `X ≃ₜ s` is `X ≃ₜ (Set.range f)`
    -- So e is exactly the right type
    exact ⟨e, trivial⟩
  · -- Empty case: X is empty, use empty_homeomorph_empty_hilbertCube
    haveI : IsEmpty X := not_nonempty_iff.mp h
    obtain ⟨e, _⟩ := empty_homeomorph_empty_hilbertCube (X := X)
    refine ⟨(∅ : Set HilbertCube), ?_, ?_⟩
    · -- MeasurableSet ∅
      exact MeasurableSet.empty
    · -- X ≃ₜ (∅ : Set HilbertCube)
      exact ⟨e, trivial⟩

end

/-- Theorem A1.2 (Polish and Borel spaces)
Every Borel subset of a Polish space is a Borel space. -/
theorem kallenberg_a1_2
    {X : Type*} [TopologicalSpace X] [MeasurableSpace X] [BorelSpace X]
    [PolishSpace X] {s : Set X} (hs : MeasurableSet s) :
    StandardBorelSpace s := by
  haveI : StandardBorelSpace X := by infer_instance
  exact hs.standardBorel

/-- Theorem A1.3 (range and inverse, Kuratowski)
Let f be a measurable bijection between two Borel spaces S and T.
Then the inverse f⁻¹ : T → S is again measurable. -/
theorem kallenberg_a1_3
    {S T : Type*} [TopologicalSpace S] [TopologicalSpace T]
    [MeasurableSpace S] [MeasurableSpace T] [BorelSpace S] [BorelSpace T]
    [StandardBorelSpace S] [StandardBorelSpace T] [Nonempty S]
    (f : S → T) (hf : Measurable f) (hf_bij : Function.Bijective f) :
    Measurable (Function.invFun f) := by
  have hf_inj : Function.Injective f := hf_bij.injective
  have hf_surj : Function.Surjective f := hf_bij.surjective
  let e : S ≃ T := Equiv.ofBijective f hf_bij
  have h_measEmb : MeasurableEmbedding f := hf.measurableEmbedding hf_inj
  have h_inv_meas : Measurable (h_measEmb.invFun : T → S) :=
    h_measEmb.measurable_invFun
  have h_eq : (h_measEmb.invFun : T → S) = Function.invFun f := by
    ext t
    apply hf_inj
    have h_range : t ∈ Set.range f := hf_surj t
    have h1 : f (h_measEmb.invFun t) = t := by
      have h_def : h_measEmb.invFun t = h_measEmb.equivRange.symm ⟨t, h_range⟩ := by
        rw [MeasurableEmbedding.invFun]
        simp [h_range]
      rw [h_def]
      have h := h_measEmb.equivRange.apply_symm_apply (⟨t, h_range⟩ : Set.range f)
      have h' := congrArg (fun (x : Set.range f) => (x : T)) h
      rw [h_measEmb.equivRange_apply] at h'
      simpa using h'
    have h2 : f (Function.invFun f t) = t := Function.invFun_eq (hf_surj t)
    calc
      f (h_measEmb.invFun t) = t := h1
      _ = f (Function.invFun f t) := h2.symm
  simpa [h_eq] using h_inv_meas

variable {Ω S : Type*} [MeasurableSpace Ω] [MeasurableSpace S]

/-- Kallenberg's projection `π A ⊆ Ω`. -/
def proj (A : Set (Ω × S)) : Set Ω :=
  Prod.fst '' A

/-- The vertical section `A_ω = {s : S | (ω,s) ∈ A}`. -/
def verticalSection (A : Set (Ω × S)) (ω : Ω) : Set S :=
  {s : S | (ω, s) ∈ A}

/-- Almost everywhere equality of two sets. -/
def AEEqualSet (μ : Measure Ω) (B C : Set Ω) : Prop :=
  ∀ᵐ ω ∂μ, (ω ∈ B ↔ ω ∈ C)

/-- Membership in the `μ`-completion. -/
def InCompletion (μ : Measure Ω) (B : Set Ω) : Prop :=
  NullMeasurableSet B μ

/-- Kallenberg's universal completion. -/
def UniversallyMeasurableSet (B : Set Ω) : Prop :=
  ∀ μ : Measure Ω, IsProbabilityMeasure μ → InCompletion μ B

/-- Pointwise selector property on a set `B`. -/
def SelectsOnSet (A : Set (Ω × S)) (ξ : Ω → S) (B : Set Ω) : Prop :=
  ∀ ω, ω ∈ B → (ω, ξ ω) ∈ A

/-- Almost-sure selector property on `π A`. -/
def SelectsOnAE (μ : Measure Ω) (A : Set (Ω × S)) (ξ : Ω → S) : Prop :=
  ∀ᵐ ω ∂μ, ω ∈ proj A → (ω, ξ ω) ∈ A

/-- A measurable core of the projection `π A`. -/
structure ProjectionCore (μ : Measure Ω) (A : Set (Ω × S)) where
  core : Set Ω
  measurable_core : MeasurableSet core
  ae_eq_proj : AEEqualSet μ core (proj A)

/-- A measurable selector on a given set `B`. -/
structure MeasurableSelectorOn (A : Set (Ω × S)) (B : Set Ω) where
  selector : Ω → S
  measurable_selector : Measurable selector
  selects : SelectsOnSet A selector B


/-! ## Elementary set lemmas -/

theorem mem_proj_iff
    {A : Set (Ω × S)} {ω : Ω} :
    ω ∈ proj A ↔ ∃ s : S, (ω, s) ∈ A := by
  dsimp [proj]
  simp

theorem proj_eq_nonempty_verticalSection
    (A : Set (Ω × S)) :
    proj A = {ω : Ω | (verticalSection A ω).Nonempty} := by
  ext ω
  dsimp [verticalSection]
  rw [mem_proj_iff, Set.nonempty_def]
  rfl

theorem mem_verticalSection_iff
    {A : Set (Ω × S)} {ω : Ω} {s : S} :
    s ∈ verticalSection A ω ↔ (ω, s) ∈ A := by
  rfl

theorem verticalSection_nonempty_of_mem_proj
    {A : Set (Ω × S)} {ω : Ω}
    (hω : ω ∈ proj A) :
    (verticalSection A ω).Nonempty := by
  rcases (mem_proj_iff.mp hω) with ⟨s, hs⟩
  exact ⟨s, hs⟩

theorem mem_proj_of_verticalSection_nonempty
    {A : Set (Ω × S)} {ω : Ω}
    (hω : (verticalSection A ω).Nonempty) :
    ω ∈ proj A := by
  rcases hω with ⟨s, hs⟩
  apply mem_proj_iff.mpr
  exact ⟨s, hs⟩

theorem measurableSet_verticalSection
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    (ω : Ω) :
    MeasurableSet (verticalSection A ω) := by
  have h_cont : Measurable (fun (s : S) => (ω, s)) :=
    measurable_prodMk_left (x := ω)
  exact hA.preimage h_cont


/-! ## Completion bookkeeping -/

theorem inCompletion_of_measurable_aeEqual
    {μ : Measure Ω} {B C : Set Ω}
    (hB : MeasurableSet B)
    (hBC : AEEqualSet μ B C) :
    InCompletion μ C := by
  have h_null : NullMeasurableSet B μ := hB.nullMeasurableSet
  have h_ae_eq : B =ᵐ[μ] C := by
    rw [← MeasureTheory.measure_symmDiff_eq_zero_iff]
    -- Need: μ (symmDiff B C) = 0, which follows from hBC
    dsimp [AEEqualSet] at hBC
    rw [MeasureTheory.ae_iff] at hBC
    -- hBC : μ {ω | ¬ (ω ∈ B ↔ ω ∈ C)} = 0
    have h_set : {ω : Ω | ¬ (ω ∈ B ↔ ω ∈ C)} = symmDiff B C := by
      ext ω
      simp [symmDiff, Set.mem_setOf_eq]
      tauto
    rwa [h_set] at hBC
  exact h_null.congr h_ae_eq

theorem projectionCore_inCompletion
    {μ : Measure Ω} {A : Set (Ω × S)}
    (hB : ProjectionCore μ A) :
    InCompletion μ (proj A) := by
  exact inCompletion_of_measurable_aeEqual hB.measurable_core hB.ae_eq_proj

theorem selectsOnAE_of_selectsOn_core
    {μ : Measure Ω} {A : Set (Ω × S)}
    (hB : ProjectionCore μ A)
    {ξ : Ω → S}
    (hξ : SelectsOnSet A ξ hB.core) :
    SelectsOnAE μ A ξ := by
  have h_ae : ∀ᵐ ω ∂μ, ω ∈ hB.core ↔ ω ∈ proj A := hB.ae_eq_proj
  filter_upwards [h_ae] with ω hω
  intro hω_proj
  have hω_core : ω ∈ hB.core := hω.mpr hω_proj
  exact hξ ω hω_core


/-! ## Hard Lusin--Choquet--Meyer input -/

/-! ## Decomposing the hard projection/section theorem -/

/--
A stronger core: a measurable subset of `π A` that agrees with `π A`
almost everywhere.
-/
structure InnerProjectionCore (μ : Measure Ω) (A : Set (Ω × S)) where
  core : Set Ω
  measurable_core : MeasurableSet core
  subset_proj : core ⊆ proj A
  ae_eq_proj : AEEqualSet μ core (proj A)

/-- Forget that an inner core is actually contained in the projection. -/
def InnerProjectionCore.toProjectionCore
    {μ : Measure Ω} {A : Set (Ω × S)}
    (hB : InnerProjectionCore μ A) :
    ProjectionCore μ A where
  core := hB.core
  measurable_core := hB.measurable_core
  ae_eq_proj := hB.ae_eq_proj


/-! ### Step 1: reduce to code space -/

/-- Baire space, used as a universal standard Borel coding space. -/
abbrev Code : Type :=
  ℕ → ℕ

/--
Every nonempty standard Borel space is a measurable image of Baire space.
-/
theorem exists_measurable_surjection_from_code
    [StandardBorelSpace S] [Nonempty S] :
    ∃ decode : Code → S,
      Measurable decode ∧ Function.Surjective decode := by
  -- StandardBorelSpace gives a Polish topology on S whose Borel σ-algebra
  -- equals the given measurable space.
  obtain ⟨τ, hBorel, hPolish⟩ := StandardBorelSpace.polish (α := S)
  have h_surj := @PolishSpace.exists_nat_nat_continuous_surjective S τ hPolish
  obtain ⟨decode, h_cont, h_surj⟩ := h_surj
  have h_meas : Measurable decode :=
    h_cont.measurable
  exact ⟨decode, h_meas, h_surj⟩

/--
Pull back a set `A ⊆ Ω × S` along a decoding map `decode : Code → S`.
-/
def pullbackByDecode
    (A : Set (Ω × S)) (decode : Code → S) :
    Set (Ω × Code) :=
  {p : Ω × Code | (p.1, decode p.2) ∈ A}

theorem measurableSet_pullbackByDecode
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    {decode : Code → S}
    (hdecode : Measurable decode) :
    MeasurableSet (pullbackByDecode A decode) := by
  dsimp [pullbackByDecode]
  -- The map (ω, x) ↦ (ω, decode x) is measurable
  have h_meas : Measurable (fun (p : Ω × Code) => (p.1, decode p.2)) := by
    refine Measurable.prodMk ?_ ?_
    · exact measurable_fst
    · exact hdecode.comp measurable_snd
  exact hA.preimage h_meas

theorem proj_pullbackByDecode_eq
    {A : Set (Ω × S)}
    {decode : Code → S}
    (hdecode_surj : Function.Surjective decode) :
    proj (pullbackByDecode A decode) = proj A := by
  ext ω
  constructor
  · intro h
    rcases mem_proj_iff.mp h with ⟨c, hc⟩
    apply mem_proj_iff.mpr
    exact ⟨decode c, by simpa [pullbackByDecode] using hc⟩
  · intro h
    rcases mem_proj_iff.mp h with ⟨s, hs⟩
    obtain ⟨c, hc⟩ := hdecode_surj s
    apply mem_proj_iff.mpr
    exact ⟨c, by simpa [pullbackByDecode, hc] using hs⟩

def projectionCore_of_pullbackByDecode
    {μ : Measure Ω}
    {A : Set (Ω × S)}
    {decode : Code → S}
    (hdecode_surj : Function.Surjective decode)
    (hB : ProjectionCore μ (pullbackByDecode A decode)) :
    ProjectionCore μ A :=
  ProjectionCore.mk hB.core hB.measurable_core (by
    rw [← proj_pullbackByDecode_eq hdecode_surj]
    exact hB.ae_eq_proj)

def measurableSelectorOn_push_decode
    {A : Set (Ω × S)}
    {decode : Code → S}
    {B : Set Ω}
    (hdecode : Measurable decode)
    (hη : MeasurableSelectorOn (pullbackByDecode A decode) B) :
    MeasurableSelectorOn A B :=
  MeasurableSelectorOn.mk (decode ∘ hη.selector) (hdecode.comp hη.measurable_selector) (by
    intro ω hωB
    have h := hη.selects ω hωB
    simpa [pullbackByDecode] using h)


/-! ### Step 2: code-space projection core -/

/-- A finite prefix of an element of Baire space. -/
abbrev Prefix : Type :=
  Σ n : ℕ, Fin n → ℕ

/-- The length-`n` prefix of a code. -/
def codePrefix (x : Code) (n : ℕ) : Prefix :=
  ⟨n, fun i => x i⟩

/-- A Souslin scheme indexed by finite prefixes. -/
def SouslinScheme (Ω : Type*) :=
  Prefix → Set Ω

/-- The Souslin operation associated to a scheme. -/
def SouslinOperation (C : SouslinScheme Ω) : Set Ω :=
  {ω : Ω | ∃ x : Code, ∀ n : ℕ, ω ∈ C (codePrefix x n)}

/-- Measurability of every set in the scheme. -/
def MeasurableSouslinScheme (C : SouslinScheme Ω) : Prop :=
  ∀ u : Prefix, MeasurableSet (C u)

/--
For measurable `A ⊆ Ω × Code`, the projection `π A` is representable by a
measurable Souslin scheme.
-/
theorem exists_measurable_souslinScheme_for_code_projection
    {A : Set (Ω × Code)}
    (hA : MeasurableSet A) :
    ∃ C : SouslinScheme Ω,
      MeasurableSouslinScheme C ∧
      SouslinOperation C = proj A := by
  -- Construct the Souslin scheme: C(u) = proj(A ∩ (Ω × B_u))
  -- where B_u = {c | codePrefix c n = u} is the basic clopen set determined by u
  -- The equality SouslinOperation C = proj A follows formally.
  -- Measurability of each C(u) is equivalent to the projection theorem for
  -- sets whose second component is a basic clopen set.
  -- This is one of the two genuinely hard theorems (Lusin--Choquet).
  sorry

/--
An inner measurable core of an arbitrary target set.
-/
structure InnerCore (μ : Measure Ω) (E : Set Ω) where
  core : Set Ω
  measurable_core : MeasurableSet core
  subset_target : core ⊆ E
  ae_eq_target : AEEqualSet μ core E

/--
Choquet capacitability / projection-core theorem for Souslin sets.

This is one of the genuinely hard pieces.
-/
theorem exists_innerCore_of_souslinOperation
    {C : SouslinScheme Ω}
    (hC : MeasurableSouslinScheme C)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ hB : InnerCore μ (SouslinOperation C), True :=
  -- Lusin--Choquet capacitability theorem for Souslin schemes.
  -- Proves that SouslinOperation C has an inner core (measurable subset agreeing a.e.).
  -- This is the second genuinely hard theorem.
  sorry

def innerProjectionCore_of_innerCore_souslin
    {A : Set (Ω × Code)}
    {C : SouslinScheme Ω}
    (hCproj : SouslinOperation C = proj A)
    {μ : Measure Ω}
    (hB : InnerCore μ (SouslinOperation C)) :
    InnerProjectionCore μ A :=
  InnerProjectionCore.mk hB.core hB.measurable_core (by
    rw [← hCproj]
    exact hB.subset_target) (by
    rw [← hCproj]
    exact hB.ae_eq_target)

/--
Projection-core theorem in the special case `S = Code`.
-/
theorem exists_innerProjectionCore_code
    {A : Set (Ω × Code)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ hB : InnerProjectionCore μ A, True := by
  obtain ⟨C, hC_meas, hC_eq⟩ := exists_measurable_souslinScheme_for_code_projection hA
  obtain ⟨hB, _⟩ := exists_innerCore_of_souslinOperation hC_meas μ
  refine ⟨innerProjectionCore_of_innerCore_souslin hC_eq hB, trivial⟩


/-! ### Step 3: code-space measurable selector -/

theorem exists_measurableSelectorOn_code
    {A : Set (Ω × Code)}
    {B : Set Ω}
    (hA : MeasurableSet A)
    (hB_meas : MeasurableSet B)
    (hB_sub : B ⊆ proj A) :
    ∃ hξ : MeasurableSelectorOn A B, True :=
  -- Measurable selection theorem for sets with measurable projection.
  -- Given A measurable and B ⊆ proj A measurable, constructs a measurable
  -- selector ξ : Ω → Code such that (ω, ξ ω) ∈ A for ω ∈ B.
  -- This is the third genuinely hard theorem (Kuratowski--Ryll--Nardzewski).
  sorry

theorem exists_measurableSelectorOn_innerProjectionCore_code
    {A : Set (Ω × Code)}
    (hA : MeasurableSet A)
    {μ : Measure Ω}
    (hB : InnerProjectionCore μ A) :
    ∃ hξ : MeasurableSelectorOn A hB.core, True := by
  obtain ⟨hξ_code, _⟩ := exists_measurableSelectorOn_code hA hB.measurable_core hB.subset_proj
  refine ⟨hξ_code, trivial⟩

/--
Full projection-and-selector theorem in code space.
-/
theorem exists_projectionCore_and_selector_code
    {A : Set (Ω × Code)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ hB : ProjectionCore μ A,
      ∃ hξ : MeasurableSelectorOn A hB.core, True := by
  obtain ⟨hB_inner, _⟩ := exists_innerProjectionCore_code hA μ
  obtain ⟨hξ, _⟩ := exists_measurableSelectorOn_innerProjectionCore_code hA hB_inner
  refine ⟨hB_inner.toProjectionCore, hξ, trivial⟩


/-! ### Step 4: transfer back to arbitrary standard Borel spaces -/

theorem exists_projectionCore_and_selector_of_code_version
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ hB : ProjectionCore μ A,
      ∃ hξ : MeasurableSelectorOn A hB.core, True := by
  obtain ⟨decode, hdecode_meas, hdecode_surj⟩ := exists_measurable_surjection_from_code (S := S)
  have hA' : MeasurableSet (pullbackByDecode A decode) :=
    measurableSet_pullbackByDecode hA hdecode_meas
  obtain ⟨hB', hξ', _⟩ := exists_projectionCore_and_selector_code hA' μ
  let hB : ProjectionCore μ A := projectionCore_of_pullbackByDecode hdecode_surj hB'
  have hξ : MeasurableSelectorOn A hB.core :=
    measurableSelectorOn_push_decode hdecode_meas hξ'
  exact ⟨hB, hξ, trivial⟩

/--
Lusin--Choquet--Meyer projection and section theorem, core form.
-/
theorem exists_projectionCore_and_selector
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ hB : ProjectionCore μ A,
      ∃ hξ : MeasurableSelectorOn A hB.core, True :=
  exists_projectionCore_and_selector_of_code_version hA μ


/-! ## A1.4(i) -/

theorem proj_inCompletion_of_measurableSet
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    InCompletion μ (proj A) := by
  obtain ⟨hB, _, _⟩ := exists_projectionCore_and_selector hA μ
  exact projectionCore_inCompletion hB

theorem proj_universallyMeasurable_of_measurableSet
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A) :
    UniversallyMeasurableSet (proj A) := by
  intro μ _
  exact proj_inCompletion_of_measurableSet hA μ


/-! ## A1.4(ii) -/

theorem exists_measurable_selector_ae
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A)
    (μ : Measure Ω) [IsProbabilityMeasure μ] :
    ∃ ξ : Ω → S,
      Measurable ξ ∧ SelectsOnAE μ A ξ := by
  obtain ⟨hB, hξ, _⟩ := exists_projectionCore_and_selector hA μ
  refine ⟨hξ.selector, hξ.measurable_selector, ?_⟩
  exact selectsOnAE_of_selectsOn_core hB hξ.selects


/-! Theorem A1.4 (projection and sections).

Let `(Ω,F)` be a measurable space, let `S` be a Borel space, and let
`A ∈ F ⊗ S`. Then:

(i) `π A` belongs to the universal completion of `F`;

(ii) for every probability measure `μ` on `F`, there exists a random element
`ξ : Ω → S` such that `(ω, ξ ω) ∈ A` holds `μ`-a.s. on `π A`.
--/

theorem kallenberg_a1_4
    [StandardBorelSpace S] [Nonempty S]
    {A : Set (Ω × S)}
    (hA : MeasurableSet A) :
    UniversallyMeasurableSet (proj A) ∧
    ∀ μ : Measure Ω,
      IsProbabilityMeasure μ →
      ∃ ξ : Ω → S,
        Measurable ξ ∧ SelectsOnAE μ A ξ := by
  refine ⟨proj_universallyMeasurable_of_measurableSet hA, ?_⟩
  intro μ _
  exact exists_measurable_selector_ae hA μ


end Appendix1
